# Generated by Django 3.1.4 on 2021-01-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('latitude', models.FloatField(max_length=30)),
                ('longitude', models.FloatField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('buildings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcaLoc.buildings')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Academician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('buildings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AcaLoc.buildings')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
